version: "3.1"

services:
  gs-db:
    container_name: dev-gs-db
    image: postgres:16-alpine3.19
    environment:
      POSTGRES_DB: "dev_gs_db"
      POSTGES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "./postgres_data:/var/lib/postgresql/date/"
    ports:
      - "5432:5432"